### ISSUE TITLE
Proposal of a full-width userbar instead of "edit bird"

### ISSUE THREAD

**Issue by alexgleason** [torchbox/wagtail#2164]
I feel like there's a better way to do this. WordPress for instance puts a solid black bar at the top of your site when you're logged in, pushing the whole rest of the site about 30px down. This way you don't have to worry about the userbar obstructing your mouse clicks. It's annoying to have to figure out the right place to put it on a site (usually not at the top) and even then it looks weird and isn't easily made to fit into the bottom corners.

I think a horizontal bar option (similar to WordPress) would be better. What do you all think?

**Comment by JoshBarr** [comment]
It's a good idea. Pretty unobtrusive if it's only 30px. 

However, if your site includes a fixed position header, the user bar would overlap it. Any idea how Wordpress deals with that?

**Comment by alexgleason** [comment]
@JoshBarr Like this:

```css
html {
    margin-top: 32px !important;
}

#wpadminbar {
    height: 32px;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    min-width: 600px;
    z-index: 99999;
}
```

Essentially just pushes the whole site down by 32px to create a gap, then puts the bar in the bap.

**Comment by JoshBarr** [comment]
It won't push down any `position: fixed` elements, but at least the massive z-index should help the admin bar stay on the top :+1:

**Comment by alexgleason** [comment]
Ah yeah, good point. I've never had a site collide with it before. But in the rare case it can be worked around with something like

```css
html.admin-mode .my-fixed-obj {
    top: 32px;
}
```

Or if you were really paranoid use some JS that checks for the existence of the bar then loops through every element giving it a margin-top of + 32px if it's position is fixed. Not recommending, just sayin'.
