### ISSUE TITLE
Explorer menu invisible on Firefox 46

### ISSUE THREAD

**Issue by benebun** [torchbox/wagtail#2549]
Hi,

just noticed that with the new Firefox 46 (tested on Ubuntu 12.04 and Windows 7) the second level of the explorer menu is invisible but clickable (blue highlight from developer tools):

![explorer_menu_firefox](https://cloud.githubusercontent.com/assets/1321740/14952289/67ff96f0-105f-11e6-93db-e7bebe7ff728.png)

Disabling the following rule in the developer toolbar shows the sub-menu, so this seems related:
```css
.explorer ul {
  […]
  transform-style: preserve-3d;
}
```

Using Wagtail 1.3.1 (haven't had a chance to test 1.4.3).
